name: configurator-deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: production
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }} # Update the ARN of the IAM role
          role-session-name: Github
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup NodeJS
        id: setup-node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci && npm run build

      - name: Build image
        run: aws s3 sync ./build s3://aro.vision.website/