name: sites-deploy

on:
  push:
    paths:
      - sites/**
    branches: [ main ]

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ./sites

jobs:
  build:
    name: production
    runs-on: ${{ vars.RUNS_ON }}
    defaults:
      run:
        working-directory: ./sites
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }} # Update the ARN of the IAM role
          role-session-name: Github
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup NodeJS
        id: setup-node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci && npm run build

      - name: Build image
        run: aws s3 sync ./dist s3://aro.vision.website/files/works/ && aws cloudfront create-invalidation --distribution-id E1ZTMXU4FC8K7A --paths '/files/works*'